insert into book (id, title, authors) values (1, 'Pierwsza książka', 'Jan Kowalski');
insert into book (id, title, authors) values (2, 'Druga książka', 'Zbigniew Nowak');
insert into book (id, title, authors) values (3, 'Trzecia książka', 'Janusz Jankowski');
insert into book (id, title, authors) values (4, 'Opowiadania najlepsze', 'Philip K. Dick');
insert into book (id, title, authors) values (5, 'Pan Lodowego Ogrodu', 'Jarosław Grzędowicz');
insert into book (id, title, authors) values (6, 'METRO 2033', 'Dmitry Glukhovsky');
insert into book (id, title, authors) values (7, 'Starość aksolotla', 'Jacek Dukaj');
insert into book (id, title, authors) values (8, 'W kraju niewiernych', 'Jacek Dukaj');
insert into book (id, title, authors) values (9, 'Limes inferior', 'Janusz A. Zajdel');
insert into book (id, title, authors) values (10, 'Taniec ze smokami: Część I', 'George R. R. Martin');
insert into book (id, title, authors) values (11, 'Taniec ze smokami: Część II', 'George R. R. Martin');
insert into book (id, title, authors) values (12, 'Na wschód od Edenu', 'John Steinback');
insert into book (id, title, authors) values (13, 'Pies Baskerville''ów', 'Arthur Conan Doyle');
insert into book (id, title, authors) values (14, 'Lód', 'Jacek Dukaj');
insert into book (id, title, authors) values (15, 'Dzienniki gwiazdowe', 'Stanisław Lem');
insert into book (id, title, authors) values (16, 'Nędznicy', 'Victor Hugo');
